### ISSUE TITLE
No license listed.

### ISSUE THREAD

**Issue by jdub01010101** [jonls/lpd-monitor#3]
Greetings.

I am not seeing a license on this, and would very much like to go over this code and possibly hack on it since I am new to Python.

If there is one and I have missed it, please close this saying so.

Thanks.

**Comment by jonls** [comment]
The dependencies are all LGPL (as far as I can tell) so I am inclined to just put a MIT license on lpd-monitor. Would that work for you @jdub01010101 ?

**Comment by jdub01010101** [comment]
Whatever you want.  I'm cool with MIT because it is very permissive.

Thanks for looking into it. :)

**Comment by jonls** [comment]
Fixed in 60d99434253f9c694b01028056e5e42861b18a23. No problem at all :+1:
